//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimited
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public staff()
        {
            this.reorderrequests = new HashSet<reorderrequest>();
            this.salesorders = new HashSet<salesorder>();
            this.stores = new HashSet<store>();
            this.useraccounts = new HashSet<useraccount>();
        }
    
        public int StaffID { get; set; }
        public string StaffName { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int Tel { get; set; }
        public string Email { get; set; }
        public string Position { get; set; }
        public string Depart { get; set; }
        public Nullable<int> Salary { get; set; }
    
        public virtual ICollection<reorderrequest> reorderrequests { get; set; }
        public virtual ICollection<salesorder> salesorders { get; set; }
        public virtual ICollection<store> stores { get; set; }
        public virtual ICollection<useraccount> useraccounts { get; set; }
    }
}
