//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class LstDept
    {
        public LstDept()
        {
            this.LstRoles = new HashSet<LstRole>();
            this.LstStaffs = new HashSet<LstStaff>();
        }
    
        public string DeptID { get; set; }
        public string DeptName { get; set; }
    
        public virtual ICollection<LstRole> LstRoles { get; set; }
        public virtual ICollection<LstStaff> LstStaffs { get; set; }
    }
}
