//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class LstItem
    {
        public LstItem()
        {
            this.RcdSalesItems = new HashSet<RcdSalesItem>();
        }
    
        public string ItemID { get; set; }
        public string ItemName { get; set; }
        public string ItemDescr { get; set; }
        public int ItemAmt { get; set; }
        public string ItemCat { get; set; }
        public string SupID { get; set; }
    
        public virtual LstSupplier LstSupplier { get; set; }
        public virtual ICollection<RcdSalesItem> RcdSalesItems { get; set; }
    }
}
