//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class LstRole
    {
        public LstRole()
        {
            this.LstStaffs = new HashSet<LstStaff>();
        }
    
        public string RoleID { get; set; }
        public string RoleName { get; set; }
        public string DeptID { get; set; }
        public int Salary { get; set; }
    
        public virtual LstDept LstDept { get; set; }
        public virtual ICollection<LstStaff> LstStaffs { get; set; }
    }
}
