//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class LstStore
    {
        public LstStore()
        {
            this.RcdSales = new HashSet<RcdSale>();
        }
    
        public string StoID { get; set; }
        public string StoAddress { get; set; }
        public int StoTel { get; set; }
        public string MgrID { get; set; }
    
        public virtual LstStaff LstStaff { get; set; }
        public virtual ICollection<RcdSale> RcdSales { get; set; }
    }
}
