//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sql6494233Entities : DbContext
    {
        public sql6494233Entities()
            : base("name=sql6494233Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<LstDept> LstDepts { get; set; }
        public DbSet<LstItem> LstItems { get; set; }
        public DbSet<LstRole> LstRoles { get; set; }
        public DbSet<LstStaff> LstStaffs { get; set; }
        public DbSet<LstStore> LstStores { get; set; }
        public DbSet<LstSupplier> LstSuppliers { get; set; }
        public DbSet<LstTest> LstTests { get; set; }
        public DbSet<RcdSale> RcdSales { get; set; }
        public DbSet<RcdSalesItem> RcdSalesItems { get; set; }
    }
}
