//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class RcdSalesItem
    {
        public string SalesID { get; set; }
        public string ItemID { get; set; }
        public int Qty { get; set; }
    
        public virtual LstItem LstItem { get; set; }
        public virtual RcdSale RcdSale { get; set; }
    }
}
