//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class RcdSale
    {
        public RcdSale()
        {
            this.RcdSalesItems = new HashSet<RcdSalesItem>();
        }
    
        public string SalesID { get; set; }
        public string StoID { get; set; }
        public string StaffID { get; set; }
        public int PaidAmt { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public System.DateTime ExpDate { get; set; }
    
        public virtual LstStaff LstStaff { get; set; }
        public virtual LstStore LstStore { get; set; }
        public virtual ICollection<RcdSalesItem> RcdSalesItems { get; set; }
    }
}
